### PR TITLE
Mobile version

### PR DESCRIPTION
**Pull request by Rizk100**
In this branch I:
* Created the works section according to the FIGMA template.
* Created the About myself section.

### CODE REVIEW

**Review by Div685 — CHANGES_REQUESTED** [review]
# 🟠 Project Invalid! ⚓

Hi, **@Rizk100**, I'm Divyesh your reviewer for this PR :man_technologist: 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that does not meet the GitHub Flow requirement. You instead used Git Flow. Please check this [Link](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/github_flow.md) to learn more about GitHub flow. 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

_(Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.)_

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by muneebulrehman — COMMENTED** [review]
Hi @Rizk100 , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that uses git-flow instead of GitHub flow. Lemme explain. In Github flow, the `main` branch should always be stable code that actually works and can be safely used. Any changes required in the application should be introduced in feature branches and approved before merging them into the main branch. But in your case, your feature branch is being merged into the `development` branch.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by Rizk100** [comment]
Merge to my main branch

**Comment by Rizk100** [comment]
Thanks but try to be specific, I can’t rewrite the whole code, how can you
help me understand how to do it better ? I tried to change the main branch
to become my default branch but it has no code in it, should I clone it on
my desktop and and introduce the code in development into it ?

**Pull request merged**
